@baseUrl = http://localhost:8080

### PDF X 1a 2001
GET {{baseUrl}}/api/pdf/standard/pdf-x-1a-2001
Accept: application/pdf

### PDF X 3 2002
GET {{baseUrl}}/api/pdf/standard/pdf-x-3-2002
Accept: application/pdf

### PDF X 4
GET {{baseUrl}}/api/pdf/standard/pdf-x-4
Accept: application/pdf

### PDF X 4p
GET {{baseUrl}}/api/pdf/standard/pdf-x-4p
Accept: application/pdf

### PDF X 5g
GET {{baseUrl}}/api/pdf/standard/pdf-x-5g
Accept: application/pdf

### PDF X 5n
GET {{baseUrl}}/api/pdf/standard/pdf-x-5n
Accept: application/pdf

### PDF X 5pg
GET {{baseUrl}}/api/pdf/standard/pdf-x-5pg
Accept: application/pdf
